version: "3.8"
services:
  map_routes_app:
    container_name: map_routes_app
    build: .
    env_file:
      - ./.env
    ports:
      - "${LISTENER_PORTS:-4000}:${FA_PORT:-5000}"
    volumes:
      - .:/app
      - node_modules:/app/node_modules  # Внешний том для node_modules

volumes:
  node_modules:  # Объявление внешнего тома node_modules